config/routes.rb
Rails.application.routes.draw do
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  resources :tweets

  root 'tweets#index'

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
	# Set association between User and Tweets
	belongs_to :user, :class_name => "User", :foreign_key => "user_id"

	validates :username, :tweetbody, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base

	# Authenticates with Twitter and get name and oauth information of user
	def self.find_or_create_from_auth_hash(auth_hash)
		user = where(provider: auth_hash[:provider], uid: auth_hash[:uid]).first_or_create
		user.update(
			name: auth_hash[:info][:nickname],
			token: auth_hash[:credentials][:token],
			secret: auth_hash[:credentials][:secret]
		)
		user
	end

	# Sets up the REST API for user to post tweets
	def twitter
		@client ||= Twitter::REST::Client.new do |config|
		  config.consumer_key        = Rails.application.secrets.twitter_api_key
		  config.consumer_secret     = Rails.application.secrets.twitter_api_secret
		  config.access_token        = token
		  config.access_token_secret = secret
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  	@current_user ||= User.find(session[:username]) if session[:username]
  end

  helper_method :current_user
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  # Create session and home timeline of the 20 most recent tweets
  # Start the daemon script to receive tweets from Twitter
  def create
    @user = User.find_or_create_from_auth_hash(auth_hash)
  	session[:username] = @user.id
    home_timeline_tweets = @user.twitter.home_timeline({:count => 20})
    home_timeline_tweets.reverse.each do |tweet|
      Tweet.create(:username => tweet.user.screen_name, :tweetbody => tweet.text)
    end
    system "ruby streaming_script.rb start"
    redirect_to root_path
  end

  # Destroy all records and stop Daemon script on logout
  def destroy
    system "ruby streaming_script.rb stop"
  	session[:username] = nil
    User.all.each do |user|
      user.destroy
    end
    User.reset_pk_sequence
    Tweet.all.each do |tweet|
      tweet.destroy
    end
    Tweet.reset_pk_sequence
  	reset_session
  	redirect_to root_path
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  respond_to :html
  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all.reverse
    respond_with(@tweets)
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    respond_with(@tweet)
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
    respond_with(@tweet)
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.username == nil
      # This is for the current user posting tweets
      @tweet.username = current_user.name
      @tweet.user_id = current_user.id
      # Updates to Twitter
      current_user.twitter.update(@tweet.tweetbody)
    else 
      # Incoming tweets from the daemon script
      @tweet.save
    end
    respond_with(@tweet)
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    @tweet.update(tweet_params)
    respond_with(@tweet)
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_with(@tweet)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:username, :tweetbody)
    end

  helper_method :refresh
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter Client</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <% if current_user %>
        <p class="navbar-text navbar-right">Signed in as <%= current_user.name %></p>
      <% end %>
    </div>
  </div>
</nav>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any?%>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :tweetbody %><br>
    <%= f.text_field :tweetbody %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tweet Client</h1>

<% if current_user %> 
  <%= link_to "Logout of Twitter", "/logout" %>
  <%= link_to 'New Tweet', new_tweet_path %>
  <table>
    <thead>
      <tr>
        <th>Username</th>
        <th>Tweetbody</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @tweets.each do |tweet| %>
        <tr>
          <td><%= tweet.username %></td>
          <td><%= tweet.tweetbody %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
<% else %>
  <%= link_to "Login to Twitter", "/auth/twitter" %>
<% end%>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @tweet.username %>
</p>

<p>
  <strong>Tweetbody:</strong>
  <%= @tweet.tweetbody %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>